name: claco_store
description: "A new Flutter project."
publish_to: 'none' # Set to 'none' if you're not publishing the app to any package repository
version: 1.0.0+1

environment:
  sdk: '>=2.12.0 <3.0.0' # Specify the minimum and maximum version of the Flutter SDK

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^0.8.5+3
  carousel_slider: ^4.0.0
  cupertino_icons: ^1.0.6
  pdf: ^3.10.8
  path_provider: ^2.1.3
  webview_flutter: ^2.0.13
  url_launcher: ^6.0.0
  share: ^2.0.4
  font_awesome_flutter: ^9.2.0
  http: ^0.13.3
  shared_preferences: ^2.1.0
  flutter_html: ^3.0.0-beta.2
  xml: ^6.3.0
  smooth_page_indicator: ^1.1.0
  cached_network_image: ^3.0.0
  firebase_core: ^2.32.0
  cloud_firestore: ^4.17.5
  firebase_storage: ^11.2.11
  firebase_dynamic_links: ^5.3.1
  flip_card: ^0.7.0
  qr_code_scanner: ^1.0.1
  speech_to_text: ^6.0.0
  avatar_glow: ^3.0.1
  qr_flutter: ^4.1.0
  location:  ^6.0.2
  geolocator: ^12.0.0
  geocoding: ^3.0.0
  permission_handler: ^11.3.1
  google_maps_webservice: ^0.0.19
  google_place: ^0.4.7
  autocomplete_textfield: ^2.0.1
  another_stepper: ^1.2.2



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

assets:
  - assets/images/
  - assets/images/Clacologo.png

flutter:
  uses-material-design: true
