name: claco_store
description: "A new Flutter project."
publish_to: 'none' # Set to 'none' if you're not publishing the app to any package repository

version: 1.0.0+1

environment:
  sdk: '>=2.12.0 <3.0.0' # Specify the minimum and maximum version of the Flutter SDK

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.1

  # Dependencies for carousel slider, icons, PDF handling, webview, URL launching, sharing, and Font Awesome icons
  carousel_slider: ^4.2.1 # Dependency for carousel slider widget
  cupertino_icons: ^1.0.8 # Dependency for Cupertino icons
  pdf: ^3.10.8 # Dependency for handling PDF files
  path_provider: ^2.1.3 # Dependency for accessing file system paths
  webview_flutter: ^4.7.0 # Dependency for displaying web content within the app
  url_launcher: ^6.2.6 # Dependency for launching URLs
  share: ^2.0.4 # Dependency for sharing content from the app
  font_awesome_flutter: ^10.7.0 # Dependency for Font Awesome icons
  cloud_firestore: ^4.17.3 # Dependency for Cloud Firestore

dev_dependencies:
  flutter_test:
    sdk: flutter # Include flutter_test as a development dependency
  flutter_lints: ^3.0.2 # Include flutter_lints for linting checks

assets:
  - assets/images/ # Include assets folder with images

flutter:
  uses-material-design: true # Use material design for the app UI
