name: claco_store
description: "A new Flutter project."
publish_to: 'none' # Set to 'none' if you're not publishing the app to any package repository
version: 1.0.0+1

environment:
  sdk: '>=2.12.0 <3.0.0' # Specify the minimum and maximum version of the Flutter SDK

dependencies:
  flutter:
    sdk: flutter
  firebase_auth: ^4.5.0
  image_picker: ^0.8.4+4

 # Include the Flutter SDK as a dependency

  # Dependencies for carousel slider, icons, pdf handling, webview, url launching, sharing, font awesome icons, and HTTP requests
  carousel_slider: ^4.0.0 # Dependency for carousel slider widget
  cupertino_icons: ^1.0.6 # Dependency for Cupertino icons
  http:
  pdf: ^3.10.8 # Dependency for handling PDF files
  path_provider: ^2.1.3 # Dependency for accessing file system paths
  webview_flutter: ^2.0.13 # Dependency for displaying web content within the app
  url_launcher: ^6.0.0 # Dependency for launching URLs
  share: ^2.0.4 # Dependency for sharing content from the app
  font_awesome_flutter: ^9.2.0 # Dependency for Font Awesome icons
  http: ^0.13.3 # Dependency for making HTTP requests

dev_dependencies:
  flutter_test:
    sdk: flutter # Include flutter_test as a development dependency
  flutter_lints: ^3.0.0 # Include flutter_lints for linting checks

assets:
  - assets/images/ # Include assets folder with images

flutter:
  uses-material-design: true # Use material design for the app UI
